#!/usr/bin/env python3
"""
Generate a (p,q)-torus knot on S³ and write .obj, .vect, and scene.txt.

Canonical Clifford-torus embedding of T(p,q) in S³ ⊂ ℝ⁴:

    γ(t) = ( cos(p·t)/√2,  sin(p·t)/√2,
             cos(q·t)/√2,  sin(q·t)/√2 ),   t ∈ [0, 2π)

Stereographic projection from north pole N = (0,0,0,1):

    π(x₁,x₂,x₃,x₄) = (x₁, x₂, x₃) / (1 − x₄)

Usage:
    python3 knots/generate.py 2 3
    python3 knots/generate.py 3 5 --n 400 --out output/T3_5
"""

import argparse
import math
import os
import sys

import numpy as np


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------

def _torus_knot_s3_uniform_t(p: int, q: int, m: int) -> np.ndarray:
    """(m, 4) unit points on S³ for T(p,q), sampled uniformly in the parameter t."""
    t = np.linspace(0.0, 2.0 * math.pi, m, endpoint=False)
    inv_sqrt2 = 1.0 / math.sqrt(2.0)
    return np.column_stack([
        inv_sqrt2 * np.cos(p * t),
        inv_sqrt2 * np.sin(p * t),
        inv_sqrt2 * np.cos(q * t),
        inv_sqrt2 * np.sin(q * t),
    ])


def torus_knot_s3(p: int, q: int, n_points: int = 200,
                  oversample: int = 64) -> np.ndarray:
    """Return (n_points, 4) unit points on S³ parametrising T(p,q), spaced at
    EQUAL geodesic arc length on S³.

    Sampling uniformly in the parameter t clusters vertices wherever the curve
    moves slowly (the q-direction wobble of T(2,q) is a strong example), and the
    stereographic image distorts this further — so a uniform-t initialisation
    looks lopsided, with one lobe point-starved and another over-dense. That
    asymmetry then biases the early energy flow and the diagnostics. We instead
    oversample densely in t, measure the cumulative geodesic length on S³, and
    re-pick n_points at equal arc length (slerping along each dense geodesic
    edge). This is exactly the parametrisation reparametrize_s3() maintains in
    the C++ optimiser, so the knot now STARTS uniform rather than being dragged
    there over the first ~50 iterations.
    """
    m = max(n_points * oversample, n_points)
    dense = _torus_knot_s3_uniform_t(p, q, m)              # (m,4) on S³

    # Geodesic length of each closed edge:  θ_k = arccos⟨x_k, x_{k+1}⟩.
    cdot = np.clip(np.einsum("ij,ij->i", dense, np.roll(dense, -1, axis=0)),
                   -1.0, 1.0)
    seg = np.arccos(cdot)
    cum = np.concatenate([[0.0], np.cumsum(seg)])           # (m+1,)
    total = cum[-1]

    targets = np.linspace(0.0, total, n_points, endpoint=False)
    j = np.clip(np.searchsorted(cum, targets, side="right") - 1, 0, m - 1)
    th = seg[j]
    f = np.where(th > 1e-12, (targets - cum[j]) / np.where(th > 1e-12, th, 1.0), 0.0)

    a = dense[j]
    b = dense[(j + 1) % m]
    sn = np.sin(th)
    w0 = np.where(th > 1e-12, np.sin((1.0 - f) * th) / np.where(sn > 1e-12, sn, 1.0), 1.0)
    w1 = np.where(th > 1e-12, np.sin(f * th) / np.where(sn > 1e-12, sn, 1.0), 0.0)
    out = w0[:, None] * a + w1[:, None] * b                 # slerp on each edge
    out /= np.linalg.norm(out, axis=1, keepdims=True)
    return out


def s3_to_r3(pts: np.ndarray) -> np.ndarray:
    """
    Stereographic projection S³ → ℝ³ from north pole N = (0,0,0,1).

    Parameters
    ----------
    pts : (N, 4) array of unit vectors on S³

    Returns
    -------
    (N, 3) array in ℝ³
    """
    x4 = pts[:, 3]
    denom = 1.0 - x4
    if np.any(np.abs(denom) < 1e-12):
        raise ValueError(
            "One or more points is at/near the north pole — "
            "projection is undefined. Perturb p, q, or n_points."
        )
    return pts[:, :3] / denom[:, np.newaxis]


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------

def write_obj(pts_r3: np.ndarray, path: str, p: int, q: int) -> None:
    """Wavefront OBJ: vertices + closed polyline edges."""
    n = len(pts_r3)
    with open(path, "w") as f:
        f.write(f"# T({p},{q}) torus knot — generated by knots/generate.py\n")
        f.write(f"# {n} vertices\n\n")
        for x, y, z in pts_r3:
            f.write(f"v {x:.10f} {y:.10f} {z:.10f}\n")
        f.write("\n")
        for i in range(n):
            j = (i + 1) % n + 1   # 1-indexed next vertex; wraps n → 1
            f.write(f"l {i + 1} {j}\n")


def write_vect(pts_r3: np.ndarray, path: str) -> None:
    """
    .vect format — single-component closed curve:

        <n_components>
        <n_points>
        x y z
        ...
    """
    n = len(pts_r3)
    with open(path, "w") as f:
        f.write("1\n")
        f.write(f"{n}\n")
        for x, y, z in pts_r3:
            f.write(f"{x:.10f} {y:.10f} {z:.10f}\n")


def write_scene(pts_r3: np.ndarray, path: str, p: int, q: int,
                obj_name: str) -> None:
    """
    scene.txt for repulsive-curves (rcurves_app).

    The first line names the OBJ file (relative to scene.txt).
    Then repulsion parameters and constraints follow.
    """
    with open(path, "w") as f:
        f.write(f"# T({p},{q}) torus knot scene for rcurves_app\n")
        f.write(f"curve {obj_name}\n")
        f.write("repel_curve 3 6\n")      # tangent-point exponents α=3, β=6
        f.write("fix_barycenter\n")
        f.write(f"fix_totallength 2\n")   # normalise to length 2


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate T(p,q) torus knot → .obj, .vect, scene.txt"
    )
    parser.add_argument("p", type=int, help="First torus-knot parameter (p > 0)")
    parser.add_argument("q", type=int, help="Second torus-knot parameter (q > 0, gcd(p,q)=1)")
    parser.add_argument("--n", type=int, default=200,
                        help="Number of sample points (default: 200)")
    parser.add_argument("--out", type=str, default=".",
                        help="Output directory (default: current directory)")
    args = parser.parse_args()

    if args.p <= 0 or args.q <= 0:
        parser.error("p and q must be positive integers")
    g = math.gcd(args.p, args.q)
    if g != 1:
        print(
            f"Warning: gcd({args.p},{args.q}) = {g} ≠ 1 "
            "— this is a link, not a knot.",
            file=sys.stderr,
        )

    os.makedirs(args.out, exist_ok=True)
    prefix = f"T{args.p}_{args.q}"

    s3_pts = torus_knot_s3(args.p, args.q, args.n)
    r3_pts = s3_to_r3(s3_pts)

    obj_path   = os.path.join(args.out, f"{prefix}.obj")
    vect_path  = os.path.join(args.out, f"{prefix}.vect")
    scene_path = os.path.join(args.out, "scene.txt")

    write_obj(r3_pts, obj_path, args.p, args.q)
    write_vect(r3_pts, vect_path)
    # scene.txt references the OBJ by filename only (same directory)
    write_scene(r3_pts, scene_path, args.p, args.q, f"{prefix}.obj")

    print(f"T({args.p},{args.q}) knot  —  {args.n} points")
    print(f"  OBJ:   {obj_path}")
    print(f"  VECT:  {vect_path}")
    print(f"  Scene: {scene_path}")


if __name__ == "__main__":
    main()
